"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

George Colon Jr
"""

if __name__ == '__main__':
    int_temp = 0
    int_temp2 = 1
    int_temp3 = 0
    fib_sum = 0
    while fib_sum < 4000000:
        int_temp3 = int_temp + int_temp2
        int_temp = int_temp2
        int_temp2 = int_temp3
        if int_temp3 % 2 == 0:
            fib_sum += int_temp3
print(fib_sum)
